---
- hosts: all
  become: true
  tasks:
    - name: install updates (Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Debian"]

    - name: install updates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Ubuntu"]

- hosts: web_servers
  become: true
  tasks:
    - name: install apache2 and php for Ubuntu
      tags: apache, apache2, ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu"]

    - name: install nginx and htop for Debian
      tags: nginx, htop, debian
      apt:
        name:
          - nginx
          - htop
        state: latest
      when: ansible_distribution in ["Debian"]

    - name: copy default html file for site
      tags: apache, nginx, ubuntu, debian
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mysql-server for Ubuntu
      tags: mysql, ubuntu
      apt:
        name: mysql-server
        state: latest
      when: ansible_distribution in ["Ubuntu"]

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package for Ubuntu
      tags: samba, ubuntu
      apt:
        name: samba
        state: latest
      when: ansible_distribution in ["Ubuntu"]
